name: Auto-assign issue

on:
  issues:
    types: [opened]

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v1.10.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: SoheilSalmani
