name: Check secret level

on: [workflow_dispatch]

jobs:
  check_secret_level:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check secret level
        run: |
          echo 'Is it a repository secret? ${{ secrets.MY_SECRET == 'REPOSITORY_LEVEL'}}'


