name: Check secret value

on: [workflow_dispatch]

jobs:
  show_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret level
        run: |
          echo 'Is it a repository secret? ${{ secrets.MY_SECRET == 'REPOSITORY_LEVEL'}}


