name: Show Python version

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: Python version
        required: true
        default: "3.10"

jobs:
  show_version:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python ${{ github.event.inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python_version }}

      - name: Print `HOME`, `GITHUB_WORKSPACE` and `GITHUB_EVENT_PATH`
        run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
          echo $GITHUB_EVENT_PATH

      - name: Show Python version
        run: python --version

      - name: Print `HOME`, `GITHUB_WORKSPACE` and `GITHUB_EVENT_PATH`
        run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
          echo $GITHUB_EVENT_PATH
